<?php

return [
    "magdan_w_ekraman" =>'مجدا و اكراما',
    "aliloia_fay_be" =>'الليلويا فاي بي',
    "kean_evran"=>'رشومات الحمل',
    "esbatir_agious"=>[
        ['file' => 'اسباتير اجيوس', 'label' => 'اسباتير اجيوس'],
        ['file' => 'اسباتير الكبيرة',  'label' => 'اسباتير الكبيرة'],
    ],
    "Salat_AlShoakr"=>'صلاة الشكر - حضور الاسقف',
    "sotis_amin"=>'سوتيس امين',
    "ne_saviv"=>'ني صافيف',
    "naiv_santy"=>'نيف سنتي',
    "tahlil_alkhodam"=>'تحليل الخدام',
    "te_shory"=>'تي شوري',
    "hetaniat" =>[
        ['file' => 'الهيتنيات', 'label' => 'الهيتنيات'],
        ['file' => 'الهيتنيات مجمعة',  'label' => 'الهيتنيات مجمعة'],
    ],
    "be_ehmot_ghar"=>'بي اهموت غار الصغير',
    "pauline" => ['type' => 'lectionary'],
    "catholic" => ['type' => 'lectionary'],
    "marad_praxis"=>'اري باميفي',
    "praxis" => ['type' => 'lectionary'],
    "synaxarium" => ['type' => 'lectionary'],
    "mi_ghalo"=>'لحن ميغالو',
    "mohaier_abenshoais"=>'محير ابنشويس',
    "agyous"=>'اجيوس',
    "oshait_al_angeal"=>'اوشية الانجيل',
    "maro_etshasf"=>'مارo اتشاسف',
    "liturgy_psalm" => ['type' => 'lectionary'],
    "liturgy_gospel" => ['type' => 'lectionary'],
    "marad_alangel"=>'مرد إنجيل أحاد وسبوت الصوم الكبير',
    "thalath_awashy_kobar" => 'الثلاث أواشي الكبار',
    "osheait_alsalam" => 'اوشية السلام',
    "osheait_alabaa" => 'اوشية الاباء',
    "osheait_alagtmaat" => 'اوشية الاجتماعات',
    "an_sofia" => 'ان صوفيا',
    "kanon_al_eman" => 'قانون الايمان',
    "into_alsoalh" => 'الثلاث أواشي الكبار',
    "salat_alsoalh" => [
        ['file' => 'يا الله العظيم الابدي', 'label' => 'صلاة الصلح باسيلي'],
        ['file' => 'عال فوق كل قوة', 'label' => 'صلاة الصلح اخري'],
        ['file' => 'ايها الكائن', 'label' => 'صلاة صلح للابن(القداس الغريغوري)'],
        ['file' => 'ايها المسيح الهنا', 'label' => 'صلاة صلح للابن للبطريرك ساويرس'],
        ['file' => 'يا رئيس الحياة وملك الدهور', 'label' => 'صلاة صلح للاب للبطريرك ساويرس'],
        ['file' => 'يا إله المحبة', 'label' => 'صلاة صلح ليوحنا المثلث الطوبي'],
    ],
    "esbasmos_adam" => 'اسبسمس ادام للصوم الكبير',
    "khatemat_alsoalh" => 'قبلو بعضكم بعضا',
    "falnaqif_hasanan" => 'فلنقف حسنا',
    "be_shafaat_waledat_alelaah" => 'بشفاعات والدة الإله ',
    "mostahiq_w_adeel" => [
        ['file' => 'مستحق و عادل', 'label' => 'باسيلي'],
        ['file' => 'محبة الله الآب', 'label' => 'غريغوري'],
        ['file' => 'مستحق و عادل - كيرلسي', 'label' => 'كيرلسي'],
    ],
    "alaazy_yakif_amamh" => [
        ['file' => 'الذي يقف أمامه الملائكة', 'label' => 'باسيلي'],
        ['file' => 'أيها الكائن السيد الرب', 'label' => 'غريغوري'],
        ['file' => 'أنت الذي يقوم أمامك', 'label' => 'كيرلسي'],
    ],
    "alsharobeam_yasgedon_lak" => 'الشاروبيم يسجدون لك',
    "asbasmos_wates" => [
        ['file' => 'اسبسمس واطس الصوم الكبير', 'label' => 'اسبسمس واطس'],
        ['file' => 'اسبسمس واطس ثانى للصوم الكبير', 'label' => 'اسبسمس واطس ثاني'],
    ],
    "agioas_agioas" => [
        ['file' => 'اجيوس اجيوس اجيوس', 'label' => 'باسيلي'],
        ['file' => 'اجيوس اجيوس اجيوس - غريغوري', 'label' => 'غريغوري'],
        ['file' => 'اجيوس اجيوس اجيوس - كيرلسي', 'label' => 'كيرلسي'],
    ],
    "tagasad_w_tanas" => [
        ['file' => 'تجسد و تأنس', 'label' => 'باسيلي'],
        ['file' => 'أتيت إلى الذبح مثل حمل', 'label' => 'غريغوري'],
    ],
    "alrshomat" => [
        ['file' => 'الرشومات', 'label' => 'باسيلي'],
        ['file' => 'الرشومات-غريغوري', 'label' => 'غريغوري'],
    ],
    "amen_amen_amen" => 'امين امين امين',
    "ffima_nahno_aidan" => [
        ['file' => 'ففيما نحن أيضا نصنع', 'label' => 'باسيلي'],
        ['file' => 'فإذا يا سيدنا', 'label' => 'غريغوري'],
    ],
    "altalba_alawla" => [
        ['file' => 'نعم نسألك أيها المسيح', 'label' => 'الطلبة الاولي'],
        ['file' => 'لكي يكونا لنا', 'label' => 'كيرلسي'],
    ],
    "agelna_mostahkeen_kolna" => 'اجعلنا مستحقين كلنا',
    "erhamna_thoma_erhamna" => 'ارحمنا ثم اررحمنا',
    "althlath_awashy_alsoghar" => [
        ['file' => 'اوشية اهوية السماء', 'label' => 'اهوية السماء'],
        ['file' => 'الاواشي الصغار', 'label' => 'الثلاث اواشي معا'],
    ],
    "aseadha_k_meqdriha" => 'أصعدها كمقدارها كنعمتك',
    "el_magmaa" => [
        ['file' => 'المجمع الباسيلي', 'label' => 'باسيلي'],
        ['file' => 'المجمع الغريغوري', 'label' => 'غريغوري'],
    ],
    "marad_alqareouan" => 'مرد القارئون',
    "traheam" => 'التراحيم',
    "barakathom_al_mpkadasa" => 'مرد بركاتهم المقدسة',
    "intro_qisma" => [
        ['file' => 'مقدمة القسمة باسيلي', 'label' => 'باسيلي'],
    ],
    "el_qisma" => [
        ['file' => 'قسمة للآب في الصوم الكبير المقدس', 'label' => 'قسمة للآب في الصوم الكبير المقدس'],
        ['file' => 'قسمة للإبن في أيام صوم الأربعين المقدس', 'label' => 'قسمة للإبن في أيام صوم الأربعين المقدس'],
    ],
    "salat_khodoaa_llab" => 'صلاة خضوع للاب',
    "alqodsat_llqediseen" => 'القدسات للقديسين',
    "alaatraaf" => 'الاعتراف',
];
